package uiGrafica.administrador;

import InterfazUsuario.CU_AdministrarMesas.Controlador_AdministrarMesas;
import static java.awt.image.ImageObserver.ABORT;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.Administrador;
import Modelo.ManoRonda;
import Modelo.MesaPoker;
import InterfazUsuario.CU_AdministrarMesas.Vista_AdministrarMesas;
import Modelo.PokerException;
import Modelo.Sesion;

/**
 *
 * @author Emilia
 */
public class AdministracionMesas extends javax.swing.JDialog implements Vista_AdministrarMesas {

    /**
     * Creates new form AdministracionMesas
     */
    private Controlador_AdministrarMesas controlador;

    public AdministracionMesas(java.awt.Frame parent, boolean modal, Sesion sesion) throws PokerException {
        super(parent, modal);
        initComponents();
        Administrador usuario = (Administrador) sesion.getUsuario();
        controlador = new Controlador_AdministrarMesas(this, sesion);
        setTitle("Administrar Mesas -  " + controlador.obtenerNombreCompletoAdministrador());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_mesas = new javax.swing.JTable();
        btn_verManos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_manos = new javax.swing.JList();
        btn_crearMesa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_totalMesas = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabla_mesas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tabla_mesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tabla_mesas.setToolTipText("Lista de mesas definidas.");
        tabla_mesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabla_mesas);

        btn_verManos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_verManos.setText("Ver Manos");
        btn_verManos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verManosActionPerformed(evt);
            }
        });

        lista_manos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(lista_manos);

        btn_crearMesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_crearMesa.setText("Crear Mesa");
        btn_crearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearMesaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Total recudado en todas las mesas: ");

        label_totalMesas.setText(".............................................");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_totalMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btn_crearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_verManos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_totalMesas))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearMesa)
                    .addComponent(btn_verManos))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verManosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verManosActionPerformed
        // TODO add your handling code here:
        int op = tabla_mesas.getSelectedRow();
        controlador.verManosDeMesa(op);
    }//GEN-LAST:event_btn_verManosActionPerformed

    private void btn_crearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearMesaActionPerformed
        controlador.crearNuevaMesa();
    }//GEN-LAST:event_btn_crearMesaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearMesa;
    private javax.swing.JButton btn_verManos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_totalMesas;
    private javax.swing.JList lista_manos;
    private javax.swing.JTable tabla_mesas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMesas(ArrayList<MesaPoker> mesasPoker) {
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("No.Mesa");
        datos.addColumn("Jugadores Req.");
        datos.addColumn("$ Ap.Base");
        datos.addColumn("# jugadores");
        datos.addColumn("No.Mano");
        datos.addColumn("Total Apostado");
        datos.addColumn("% Comision");
        datos.addColumn("$ Total");
        datos.addColumn("Estado");
        datos.setRowCount(ABORT); // limpia la tabla 
        int fila = 0;
        for (MesaPoker m : mesasPoker) {
            datos.setValueAt(m.getId(), fila, 0);
            datos.setValueAt(m.getJugadoresRequeridos(), fila, 1);
            datos.setValueAt(m.getLuz(), fila, 2);
            datos.setValueAt(m.getJugadoresMesa().size(), fila, 3);
            datos.setValueAt(0, fila, 4);
            datos.setValueAt(m.totalRecaudado(), fila, 5);
            datos.setValueAt(m.getPorcentajeComision(), fila, 6);
            datos.setValueAt(m, fila, 7);
            datos.setValueAt(m.getEstado(), fila, 8);
            fila++;
        }
        tabla_mesas.setModel(datos);
    }

    @Override
    public void cargarTotalRecaudado(double totalRecaudadoMesas) {
        label_totalMesas.setText(String.valueOf(totalRecaudadoMesas));
    }

    @Override
    public void mostrarManos(ArrayList<ManoRonda> manos) {
        lista_manos.setListData(manos.toArray());
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, getTitle(), JOptionPane.INFORMATION_MESSAGE);

    }

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, getTitle(), JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarVentanaCrearMesa(Administrador usuario) {
        new CrearMesa(null, true, usuario).setVisible(true);
    }

    @Override
    public void salir() {
        controlador.salir();
        dispose();
    }
}
