package uiGrafica.administrador;

import InterfazUsuario.CU_CrearMesa.Controlador_CrearMesa;
import InterfazUsuario.CU_CrearMesa.Vista_CrearMesa;
import Modelo.Administrador;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Emilia
 */
public class CrearMesa extends javax.swing.JDialog implements Vista_CrearMesa {

    /**
     * Creates new form CrearMesa
     */
    private Controlador_CrearMesa controlador;

    public CrearMesa(java.awt.Frame parent, boolean modal, Administrador usuario) {
        super(parent, modal);
        initComponents();
        controlador = new Controlador_CrearMesa(this, usuario);
        setLocationRelativeTo(parent);
        setTitle("Administrador : " + usuario.getNombreCompleto());
        btn_crearMesa.setEnabled(false);

        agregarEscuchadores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_jugadoresRequeridos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_apuestaBase = new javax.swing.JTextField();
        tf_comision = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_crearMesa = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("# Jugadores requeridos : ");

        jLabel2.setText("Monto apuesta base : ");

        tf_comision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_comisionActionPerformed(evt);
            }
        });

        jLabel3.setText("Porcentaje de comision :");

        btn_crearMesa.setText("Crear Mesa");
        btn_crearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearMesaActionPerformed(evt);
            }
        });

        btn_salir.setText("Volver");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_crearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_comision, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_jugadoresRequeridos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apuestaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_jugadoresRequeridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_apuestaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearMesa)
                    .addComponent(btn_salir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearMesaActionPerformed
        // TODO add your handling code here:
        crearMesa();
    }//GEN-LAST:event_btn_crearMesaActionPerformed

    private void tf_comisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_comisionActionPerformed
        // TODO add your handling code here:
        crearMesa();

    }//GEN-LAST:event_tf_comisionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        controlador.salir();
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearMesa;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_apuestaBase;
    private javax.swing.JTextField tf_comision;
    private javax.swing.JTextField tf_jugadoresRequeridos;
    // End of variables declaration//GEN-END:variables

    private void agregarEscuchadores() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                habilitarBoton();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                habilitarBoton();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                habilitarBoton();
            }
        };

        tf_jugadoresRequeridos.getDocument().addDocumentListener(documentListener);
        tf_apuestaBase.getDocument().addDocumentListener(documentListener);
        tf_comision.getDocument().addDocumentListener(documentListener);
    }

    private void habilitarBoton() {
        boolean camposCompletos = !tf_jugadoresRequeridos.getText().trim().isEmpty()
                && !tf_apuestaBase.getText().trim().isEmpty()
                && !tf_comision.getText().trim().isEmpty();
        btn_crearMesa.setEnabled(camposCompletos);
    }

    private void crearMesa() {
        try {
            int jugadoresRequeridos = (int) getJugadoresRequeridos();
            double apuestaBase = (double) getApuestaBase();
            double comision = (double) getComision();
            controlador.crearMesa(jugadoresRequeridos, apuestaBase, comision);
        } catch (NumberFormatException e) {
            mostrarError("Por favor, ingrese valores numéricos válidos para todos los campos.");
        }
    }

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void prepararProximoIngreso() {
        tf_jugadoresRequeridos.setText("");
        tf_apuestaBase.setText("");
        tf_comision.setText("");
        btn_crearMesa.setEnabled(false);
    }

    @Override
    public int getJugadoresRequeridos() {
        return Integer.parseInt(tf_jugadoresRequeridos.getText());
    }

    @Override
    public double getApuestaBase() {
        return Double.parseDouble(tf_apuestaBase.getText());
    }

    @Override
    public double getComision() {
        return Double.parseDouble(tf_comision.getText());
    }

    @Override
    public void salir() {
    }
}
